[package]
name = "json-schema-to-c"
version = "0.1.0"
authors = ["zhangchao <zhangchao@joycode.art>"]
edition = "2018"
exclude = ["./build", "./deps"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file = "1.0.0"
